- name: Baremetal | Insert Virtual Media
  community.general.redfish_command:
    category: Manager
    command: VirtualMediaInsert
    baseuri: "{{ item.bmc_address }}"
    username: "{{ item.bmc_username }}"
    password: "{{ item.bmc_password | d(baremetal_bmc_password) }}"
    virtual_media:
      image_url: 'http://{{ ansible_host }}:{{ openshift_agent_iso_httpd_port }}/agent.x86_64.iso'
      media_types:
        - CD
    resource_id: "{{ item.bmc_resource_id | default(omit) }}"
  when:
    - (item.kubevirt is not defined or not item.kubevirt)

- name: Baremetal | Set Next One-Time Boot to CD/DVD
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    baseuri: "{{ item.bmc_address }}"
    username: "{{ item.bmc_username }}"
    password: "{{ item.bmc_password | d(baremetal_bmc_password) }}"
    bootdevice: Cd
    resource_id: "{{ item.bmc_resource_id | default(omit) }}"
  when:
    - baremetal_set_onetime_boot
    - (item.kubevirt is not defined or not item.kubevirt)

- name: Baremetal | Reboot the system
  community.general.redfish_command:
    category: Systems
    command: "{{ baremetal_power_cmd | default('PowerReboot') }}"
    baseuri: "{{ item.bmc_address }}"
    username: "{{ item.bmc_username }}"
    password: "{{ item.bmc_password | d(baremetal_bmc_password) }}"
    resource_id: "{{ item.bmc_resource_id | default(omit) }}"
  when:
    - (item.kubevirt is not defined or not item.kubevirt)
