- name: add ipv4 dhcp fixed address reservation
  infoblox.nios_modules.nios_fixed_address:
    name: "{{ item.name }}"
    ipaddr: "{{ item.ipaddr }}"
    mac: "{{ item.macaddr }}"
    options:
      - num: 12
        value: "{{ item.name }}"
    network: "{{ openshift_install_network }}"
    network_view: default
    state: present
    provider: "{{ dns_provider }}"
  loop: "{{ dns_nodes }}"