- name: Create | Include request IPs
  ansible.builtin.include_tasks: request_ips.yml

- name: Create | Include create records
  ansible.builtin.include_tasks: create_records.yml

- name: Create | include fixed addresses
  ansible.builtin.incluider_tasks: fixed_address.yml
  when: openshift_install_dhcp

- name: Create | Update openshift_install_nodes in case run as part of collection
  ansible.builtin.set_fact:
    openshift_install_nodes: "{{ dns_nodes }}"